services:
  - type: web
    name: gemini-chatbot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: GEMINI_API_KEY
        value: AIzaSyCb2qfj-XKZo1U86JCwHOjNOAHeKlw-P4I
